FROM node:20-alpine

WORKDIR /app

COPY frontend/package*.json ./
RUN npm ci

COPY frontend ./

ARG NEXT_PUBLIC_API_HOST=http://whai_backend:8000
ENV NEXT_PUBLIC_API_HOST=$NEXT_PUBLIC_API_HOST

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
